"""Added item equipped status

Revision ID: 47979a55260f
Revises: dd529c3f9266
Create Date: 2022-04-01 15:53:26.588092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47979a55260f'
down_revision = 'dd529c3f9266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_inventory_item', sa.Column('equipped', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_inventory_item', 'equipped')
    # ### end Alembic commands ###
