"""Inventory Item multiple actions

Revision ID: 972f376a44ea
Revises: 47979a55260f
Create Date: 2022-04-02 07:36:56.831554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
import json
from sqlalchemy import bindparam


# revision identifiers, used by Alembic.
revision = '972f376a44ea'
down_revision = '47979a55260f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_item_type', sa.Column('actions', sa.String(), nullable=False, server_default='[]'))
    conn = op.get_bind()
    res = conn.execute('select id, action, action_options from inventory_item_type')
    results = res.fetchall()
    new_actions = [{'_id': r[0], 'actions': json.dumps([{'action': r[1], 'action_options': json.loads(r[2])}])}
                   for r in results if r[1]]

    inventory_item_type_table = table('inventory_item_type',
                                      column('id'),
                                      column('actions'))

    stmt = inventory_item_type_table.update().where(inventory_item_type_table.c.id == bindparam('_id')).values({
        'actions': bindparam('actions')
    })

    conn.execute(stmt, new_actions)

    op.drop_column('inventory_item_type', 'action')
    op.drop_column('inventory_item_type', 'action_options')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_item_type', sa.Column('action_options', sa.String(), nullable=False, server_default='{}'))
    op.add_column('inventory_item_type', sa.Column('action', sa.String(), nullable=False, server_default=''))
    op.drop_column('inventory_item_type', 'actions')
    # ### end Alembic commands ###
