# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node Build Frontend Dist

on:
  push:
    branches: [ master ]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '12'
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json
    - name: npm install and build
      run: |
        npm ci
        npm run build
      working-directory: ./frontend
    - name: Copy dist to webserver static
      run: |
        rm -rf ./webserver/static
        cp -r ./frontend/dist ./webserver/static
    - name: Commit static
      run: |
        git config --global user.email "Maveo@gmx.de"
        git config --global user.name "Spark Runner"
        git add --force ./webserver/static
        git diff-index --quiet HEAD || git commit -am "Automated frontend dist build" && git push
